  Running command git clone --quiet https://github.com/huggingface/transformers.git /tmp/pip-install-2ru4wxx5/transformers_37b9a085f5824aabb045aa193a943eab
  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-2ru4wxx5/peft_b070ce928a5b4abba6c259c26b1da153
  Running command git clone --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-2ru4wxx5/accelerate_4ebcad2f009346259d443ecfee985df7
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so.11.0'), PosixPath('/home/brc4cb/.conda/envs/falcon_40B/lib/libcudart.so')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/transformers/configuration_utils.py:483: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/transformers/modeling_utils.py:2192: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Loading checkpoint shards:   0%|          | 0/9 [00:00<?, ?it/s]Loading checkpoint shards:  11%|█         | 1/9 [00:07<01:01,  7.63s/it]Loading checkpoint shards:  22%|██▏       | 2/9 [00:13<00:47,  6.81s/it]Loading checkpoint shards:  33%|███▎      | 3/9 [00:20<00:39,  6.66s/it]Loading checkpoint shards:  44%|████▍     | 4/9 [00:26<00:32,  6.51s/it]Loading checkpoint shards:  56%|█████▌    | 5/9 [00:32<00:25,  6.39s/it]Loading checkpoint shards:  67%|██████▋   | 6/9 [00:39<00:19,  6.34s/it]Loading checkpoint shards:  78%|███████▊  | 7/9 [00:45<00:12,  6.50s/it]Loading checkpoint shards:  89%|████████▉ | 8/9 [00:52<00:06,  6.45s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:57<00:00,  6.08s/it]Loading checkpoint shards: 100%|██████████| 9/9 [00:57<00:00,  6.39s/it]
Traceback (most recent call last):
  File "/gpfs/gpfs0/project/SDS/research/christ_research/falcon/qlora/qlora.py", line 807, in <module>
    train()
  File "/gpfs/gpfs0/project/SDS/research/christ_research/falcon/qlora/qlora.py", line 678, in train
    data_module = make_data_module(tokenizer=tokenizer, args=args)
  File "/gpfs/gpfs0/project/SDS/research/christ_research/falcon/qlora/qlora.py", line 576, in make_data_module
    dataset = load_data(args.dataset)
  File "/gpfs/gpfs0/project/SDS/research/christ_research/falcon/qlora/qlora.py", line 540, in load_data
    raise NotImplementedError(f"Dataset {dataset_name} not implemented yet.")
NotImplementedError: Dataset = not implemented yet.
